      SUBROUTINE DSMACC_ISOROPIA (WI, RHI, TEMPI,  CNTRL,
     &                     WT, GAS, AERLIQ, AERSLD, SCASI, OTHER)
      ! INTEGER parameters
      INTEGER, PARAMETER :: NCOMP  =   8
      INTEGER, PARAMETER :: NIONS  =  10
      INTEGER, PARAMETER :: NGASAQ =   3
      INTEGER, PARAMETER :: NSLDS  =  19
      INTEGER, PARAMETER :: NPAIR  =  23
      INTEGER, PARAMETER :: NZSR   = 100
      INTEGER, PARAMETER :: NERRMX =  25
      INTEGER, PARAMETER :: NCTRL = 2, NOTHER = 9
      REAL*8, INTENT(IN) :: TEMPI, RHI
      REAL*8, INTENT(IN) :: WI(NCOMP)
      REAL*8, INTENT(IN) :: CNTRL(NCTRL)
      CHARACTER, INTENT(OUT) :: SCASI*15
      REAL*8, INTENT(OUT) :: WT(NCOMP), GAS(NGASAQ), AERSLD(NSLDS),
     &          AERLIQ(NIONS+NGASAQ+2), OTHER(NOTHER)
      CALL ISOROPIA (WI, RHI, TEMPI,  CNTRL,
     &                     WT, GAS, AERLIQ, AERSLD, SCASI, OTHER)
     
      END SUBROUTINE DSMACC_ISOROPIA